# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


# require 'open-uri'

Checkin.destroy_all
Beer.destroy_all
Brewery.destroy_all
User.destroy_all

# User Seeds

demo_user = User.create!(username: "tommy", email: "tommy@aa.io", password: "hunter2", first_name: "Tommy", last_name: "Duek", birth_date: "1990-12-30")
user1 = User.create!(username: "BeerGuy", email: "beerguy@lagerd.com", password: "hunter2", first_name: "Bob", last_name: "Belcher", birth_date: "1990-12-30")
user2 = User.create!(username: "BeerHunter234", email: "chad@lagerd.com", password: "hunter2", first_name: "Chad", last_name: "Chaddington", birth_date: "1992-8-30")
user3 = User.create!(username: "HopHead32", email: "ben@lagerd.com", password: "hunter2", first_name: "Ben", last_name: "Wyatt", birth_date: "1982-1-3")
# user4 = User.create!(username: "BeerLyfee", email: "tommy@lagerd.com", password: "hunter2", first_name: "Stephen", last_name: "DiPietro", birth_date: "1996-5-9")
# user5 = User.create!(username: "BeerChick", email: "katie@lagerd.com", password: "hunter2", first_name: "Katie", last_name: "O'Connor", birth_date: "1994-2-12")


# Brewery Seeds

other_half = Brewery.create!(name: "Other Half Brewing Co.", location: "Brooklyn, NY United States", description: "In 2014, Sam Richardson, Matt Monahan and Andrew Burman founded Other Half Brewing Company, a local brewery in New York City with a simple mission: to create beers that they wanted to drink from a company that they wanted to be a part of. Their vision was to build a passionate team that brewed great beers in the state of New York—done so with effort and thoughtfulness—to represent the “Other Half” of the industry. Today, Other Half craft beers in their Brooklyn brewery and are dedicated to collaborating with breweries both in New York as well as across the world in an effort to constantly move the industry forward while elevating the craft. The Other Half team believes that local breweries play an important role in their communities which is why they partner with these other likeminded brewers and brands in local nabes across the country and the world—but always return to their home state of New York and their Brooklyn taproom.")

grimm = Brewery.create!(name: "Grimm Artisanal Ales", location: "Brooklyn, NY United States", description: "Grimm Artisanal Ales is a Brooklyn-based brewery founded in 2013 by Joe and Lauren Grimm after nearly a decade of tinkering with fermentation. Grimm specializes in concise, elegant ales epitomizing the creative, experimental spirit of the American artisanal beer revolution. With each limited edition release, we seek to push the boundaries of style and flavor in order to create beers with the utmost depth and complexity. For five years, Grimm operated as a nomadic brewery. Joe and Lauren would develop each recipe in the kitchen of their Gowanus apartment and travel to existing breweries near and far to craft their commercial beers. In June 2018, they opened their permanent location in the East Williamsburg neighborhood of Brooklyn, NY.")

russian_river = Brewery.create!(name: "Russian River Brewing Company", location: "Windsor, CA United States", description: "Russian River Brewing Company (RRBC) was originally owned by Korbel Champagne Cellars in Guerneville, California and was founded on their historic and beautiful property amidst vineyards and redwoods near the Russian River. When Korbel decided to get out of the beer business in 2003, they generously offered the brewmaster, Vinnie Cilurzo and his wife Natalie the rights to the brand. Russian River Brewing might be something completely different now if it weren't for this incredible opportunity. In the early days on the Korbel property, Vinnie not only brewed the beer, but made the sales calls and deliveries as well. Eventually they hired a sales/delivery guy to help with all of that so he could focus on brewing! Korbel planted a small hop field where Vinnie received a 'field' education on growing and brewing with 'wet' hops. It was from those amazingly fresh hops, grown just a few yards away, that he made his first wet hops brew, 'Hop-Time Harvest Ale'. As it turns out, demand is still greater than the supply, but they prefer to grow their business organically while focusing on efficiencies and quality. For now, it is easier to make better beer than it is to make more beer! The history of Russian River Brewing Company would be incomplete without a little background on the people who own it, operate it, and are passionate about their brewery and craft beer in general!")

# alchemist = Brewery.create!(name: "The Alchemist", location: "Stowe, VT United States", description: "The Alchemist Brewery is a 15 barrel, small production brewery specializing in fresh, unfiltered IPAs.")

# allagash = Brewery.create!(name: "Allagash Brewing Company", location: "Portland, ME United States", description: "Founded in Portland, Maine, by Rob Tod, Allagash Brewing Company is dedicated to crafting the best Belgian-inspired beers in the world. Since 1995, Allagash has been a proud resident of Portland, and loves giving back to the community—and state—that has supported it along the way. Allagash currently stands as one of the Top 50 Craft Breweries in the U.S. (by sales volume) and loves to experiment in barrel-aged and spontaneously fermented beers. A portion of the proceeds from all Allagash beers goes back to organizations that help make our great state of Maine even better.")

# sierra_nevada = Brewery.create!(name: "Sierra Nevada Brewing Co.", location: "Chico, CA United States", description: "In 1980, Ken Grossman built a small brewery in the city of Chico, California. To this day, premium ingredients and time-honored brewing techniques make Sierra Nevada ales and lagers truly exceptional beers.")

# stone = Brewery.create!(name: "Stone Brewing", location: "Escondido, CA United States", description: "Founded by Greg Koch and Steve Wagner in 1996, San Diego-based Stone Brewing is the 9th largest craft brewer in the United States. Stone has been listed on the Inc. 500 | 5000 Fastest Growing Private Companies list 11 times, and has been called the “All-time Top Brewery on Planet Earth” by BeerAdvocate magazine twice. The multifaceted company will be the first American craft brewer to independently build, own and operate a brewery in Europe, and is also building a production brewery and destination restaurant in Richmond, Virginia. Brewing at both locations is anticipated to begin in spring 2016. Known for its bold, flavorful and largely hop-centric beers, Stone has earned a reputation for brewing outstanding, unique beers while maintaining an unwavering commitment to sustainability, business ethics, philanthropy and the art of brewing. ")

# lawsons = Brewery.create!(name: "Lawson's Finest Liquids", location: "Waitsfield, VT United States", description: "Lawson’s Finest Liquids produces beer of the highest quality with outstanding freshness. We emulate the best of widely appreciated styles of beer, featuring world class IPAs and unique maple brews, while quenching the thirst of beer lovers from near and far.")

# gsb = Brewery.create!(name: "Great South Bay Brewery", location: "Bay Shore, NY United States", description: "The Bay we’re talking about is the Great South Bay, 151 square miles of shallow saltwater heaven stretching to the horizon off the south shore of Long Island, New York.")

# hill_farmstead = Brewery.create!(name: "Hill Farmstead Brewery", location: "Greensboro, VT United States", description: "Hill Farmstead Brewery is the culmination of many years of travel and insight—of experience and education—of friendships and explorations. The brewery is the revival and continuation of 220 years of Hill heritage and hand crafted history in North Greensboro, Vermont. Its logo is retrieved from a sign that once hung in Aaron Hill's (our great(x3) grandfather) tavern, just up the hill, in the early 1800s.")

# cantillon = Brewery.create!(name: "Brasserie Cantillon", location: "Brussels, Région de Bruxelles-Capitale - Brussels Hoofdstedelijk Gewest Belgium", description: "Brasserie Cantillon Brewery is a small and local family brewery in the city of Anderlecht in Brussels, Belgium. Founded in 1900 by Paul Cantillon, the brewery immediately became popular for its lambic beers. Some of its remarkable lambic beers are the Cantillon Kriek, Gauze and Faro. The brewery depends on raw wheat, malted barley and dried hops. Brasserie Cantillon Brewery takes pride in its long tradition of using organic ingredients of grown cereals that promote fine quality of beers and clean agricultural practice. Spontaneous fermentation is a trademark of lambic beers produced by the brewery. Brasserie Cantillon Brewery also delivers fruit-flavored beers from oaks and wide variety of fruits.")

# founders = Brewery.create!(name: "Founders Brewing Co.", location: "Grand Rapids, MI United States", description: "We don’t brew beer for the masses. Instead, our beers are crafted for a chosen few, a small cadre of renegades and rebels who enjoy a beer that pushes the limits of what is commonly accepted as taste. In short, we make beer for people like us. Founders. Brewed for us.")

# three_floyds = Brewery.create!(name: "Three Floyds Brewing Co.", location: "Munster, IN United States", description: "Nick Floyd founded 3 Floyds in a Hammond, Indiana, garage in 1996. The then-small brewery with the 'It's Not Normal' motto set out to stand out with bold, aggressive, highly hopped beers. In 2000, 3 Floyds moved to nearby Munster, Indiana, and added a brewpub a few years later. Led by brands like Alpha King, Dark Lord, Dreadnaught, Gumballhead and Zombie Dust, 3 Floyds has grown into a world-class brewery, earning many accolades, awards and top rankings from world-recognized organizations and beer geeks alike. 3 Floyds has built an elite team of brewers, packagers, engineers and hospitality pros to continue cranking out the best beer possible.")

# firestone_walker = Brewery.create!(name: "Firestone Walker Brewing Co.", location: "Paso Robles, CA United States", description: "Firestone Walker Brewing Company started out as a small brewery in Paso Robles and Buellton in California. It was founded by Adam Firestone and David Walker in 1996. The beers from the brewery were a product of the founders’ inspiration to deliver fine quality of beers that reflects the essence of Central Coast of California Firestone Walker’s ales are carefully fermented in oak barrels. The flavors of beer crafted by Firestone Walker Brewery continue to expand in an effort to meet the expanding palates of craft beer enthusiasts within and outside of California. Firestone Walker Brewing Company has gained notoriety for its fine beers, including the ‘Mid Size Brewery of the Year’ recognition.")

# jester_king = Brewery.create!(name: "Jester King Brewing", location: "Austin, TX United States", description: "Located in the beautiful Texas Hill Country, Jester King Craft Brewery is an authentic farmhouse brewery committed to brewing artisan ales of great depth and character. At times drawing influences from the world beyond traditional brewers’ yeast, Jester King’s beer is not rushed to market but allowed to mature – often in oak barrels – to create the most enjoyable, interesting and exciting beer we can make. An additional layer of complexity is added to Jester King’s bottled beers by allowing a second fermentation to take place in the bottle. As part of its commitment to sustainability, the slow food movement and Texas, Jester King beer uses as many organic and local ingredients as possible and will soon be brewed with harvested rainwater.")

# trillium = Brewery.create!(name: "Trillium Brewing Company", location: "Canton, MA United States", description: "Trillium Brewing Company was founded by JC and Esther Tetreault, a young dumb couple in love, planning their wedding and dreaming about how they would spend their lives together. The desire to build a brewery was about more than just making beer, it was about creating a way of life and building a community with which to share experiences. A beer geek and botany nerd, JC chose the trillium flower to represent what we strive to bring to our beer and our lives: beauty, strength, simplicity, and balance. We operate a brewery and taproom in Canton, MA as well as a full service restaurant and brewery in the Fort Point neighborhood of Boston. We also operate seasonal pop-up beer gardens around the city of Boston under the Trillium Garden project.")

# tree_house = Brewery.create!(name: "Tree House Brewing Company", location: "Charlton, MA United States", description: "Tree House Brewing Company brews a vast array of ales. The offerings vary based on the season, our moods, and innovations discovered in the midst of day in and day out brewing. Our artisan brewery knows no bounds and we are driven by an intense curiosity of ingredients and how they blend together to create something special.")
# augustiner = Brewery.create!(name: "Augustiner-Bräu", location: "Munich, Bayern Germany", description: "Augustiner-Bräu is a brewery in Munich, Germany. Established in 1328, it is Munich's oldest independent brewery. The company is owned by the Edith Haberland Wagner Trust 51% and the Inselkammer-Family 49%.")

# lagunitas = Brewery.create!(name: "Lagunitas", location: "Petaluma, CA United States", description: "From points distant and beyond we all converged on Petaluma in 1993 and ’94 with an unenunciated desire to be more than we were before. The core of Lagunitas came from Chicago, St Louis, Memphis, Walker Creek, and the highlands of Quincy. The Chicago contingent initiated the brewing and the gravitational effect of its suchness did the rest. We all loved the beer but the mission was larger than the ordinary joy of a hoppy-sweet quaff. It was driven unseen by an urge to communicate with people, to find our diasporidic tribe, and to connect with other souls adrift on a culture that had lost its center and spun its inhabitants to the four winds to wander lost and bereft with a longing to re-enter the light. Beer, we have learned, has always been a good lubricant for social intercourse! The Lagunitas Brewing Co. was not so much an act of ordinary ‘foundling’ as it was willed into being by the unspoken desire of supportive beer-lovers in Northern California after which they continued to nurture their creation and urged us forward to fulfill the unifying needs of that same beer-loving diaspora from coast to coast and beyond. It is good to have friends!")

# jacks_abbey = Brewery.create!(name: "Jacks Abbey Craft Lagers", location: "Framingham, MA United States", description: "Jack's Abby is a family-owned craft brewery in Framingham, MA, brewing craft lagers with traditional German standards and American innovation.")

# Beer Seeds # STYLES = Pale Ale, Wheat, IPA, Stout, Sour, Pilsner, IPL, Brown Ale, Amber Ale, Helles Lager

beer1 = Beer.create!(name: "All Green Everything", brewery_id: other_half.id, style: "IPA", ibu: "120", description: "A huge, but dry, triple IPA packed with Motueka, Amarillo, Citra and Mosaic.", abv: "10.5")
beer2 = Beer.create!(name: "Double Dry Hopped Double Mosaic Dream", brewery_id: other_half.id, style: "IPA", ibu: "90", description: "Double Dry Hopped Double Mosaic Dream is our standard Double Mosaic dry hopped a second time with a mosaic lupulin powder. Lupulin powder is a new hop product that is similar to our standard hops but with all the extra plant filler stripped away. It’s pure hops and it’s awesome.", abv: "8.5")
beer3 = Beer.create!(name: "Green Diamonds", brewery_id: other_half.id, style: "IPA", ibu: "100", description: "An imperial IPA brewed with Golden Promise malt and lots of Australian Galaxy hops.", abv: "9.1")

beer4 = Beer.create!(name: "Double Negative", brewery_id: grimm.id, style: "Sour", ibu: "75", description: "2015 GABF gold medal and 2014 GABF silver medal in the imperial stout category. Double Negative pours jet black with burnt orange highlights. A long lasting tan head leaves abundant lacing. Aromas bursting from the glass include espresso, bitter chocolate, caramel, black currant and blueberry. Creamy and viscous on the palate, the flavor initially follows the nose. A pop of smooth bitterness comes after, and then a lingering, roasty finish.", abv: "10")
beer5 = Beer.create!(name: "Lambo Door", brewery_id: grimm.id, style: "IPA", ibu: "80", description: "We in this bitch. Finna get crunk. Gummi bear juice on fleek. Citra, Simcoe, El Dorado you already know what it is.", abv: "8")
beer6 = Beer.create!(name: "Rainbow Dome", brewery_id: grimm.id, style: "Sour", ibu: "10", description: "American wild/sour ale brewed with apricots, dry hopped with El Dorado, Columbus, and Cascade, and conditioned on oak. Crush crush crush.", abv: "5")

beer7 = Beer.create!(name: "Pliny The Elder", brewery_id: russian_river.id, style: "IPA", ibu: "100", description: "A true leader in the hop-wars of the west coast, Pliny the Elder hits you over the head with hoppy bitterness and manages to smooth the rough edges out enough to become an enjoyable brew.", abv: "8")
beer8 = Beer.create!(name: "Pliny The Younger", brewery_id: russian_river.id, style: "IPA", ibu: "90", description: "Pliny the Younger was Pliny the Elder’s nephew, in the case of this beer, the 'Younger' is a triple IPA. Pliny the Younger is hopped three times more than our standard IPA, and is dry hopped four different times.", abv: "10.25")
beer9 = Beer.create!(name: "Consecration", brewery_id: russian_river.id, style: "Sour", ibu: "10", description: "Dark Ale aged in Cabernet Sauvignon barrels from local wineries. It is aged for 4 to 8 months with black currants, brettanomyces, lactobacillus, and pediococcus added to each barrel. Rich flavors of chocolate truffle, spice, tobacco, currants, and a bit of Cabernet. Very full-bodied, sip slowly!", abv: "10")

# beer10 = Beer.create!(name: "Heady Topper", brewery_id: alchemist.id, style: "IPA", ibu: "100", description: "We love hops – that’s why our flagship Double IPA, Heady Topper, is packed full of them. Heady Topper was designed to showcase the complex flavors and aromas these flowers produce. The Alchemist has been brewing Heady Topper since 2003. This Double IPA is not intended to be the strongest or most bitter DIPA. It is brewed to give you wave after wave of hop flavor without any astringent bitterness. We brew Heady Topper with a proprietary blend of six hops – each imparting its own unique flavor and aroma. Take a big sip of Heady and see what hop flavors you can pick out. Orange? Tropical Fruit? Pink Grapefruit? Pine? Spice? There is just enough malt to give this beer some backbone, but not enough to take the hops away from the center stage.", abv: "8")
# beer11 = Beer.create!(name: "Focal Banger", brewery_id: alchemist.id, style: "IPA", ibu: "90", description: "American IPA with Citra & Mosaic hops.", abv: "7")
# beer12 = Beer.create!(name: "Luscious", brewery_id: alchemist.id, style: "Stout", ibu: "No", description: "British-style imperial stout", abv: "9.2")

# beer13 = Beer.create!(name: "White", brewery_id: allagash.id, style: "Wheat", ibu: "13", description: "Allagash White features a refreshing balance of citrus and spice. Wheat, coriander, and Curaçao orange peel round out the flavor of this pale straw-colored, hazy beer.", abv: "5.2")
# beer14 = Beer.create!(name: "Coolship Resurgam", brewery_id: allagash.id, style: "Sour", ibu: "20", description: "Coolship Resurgam is a blend of both old and young unfruited spontaneous beer. The name comes from the motto of our fair city, Portland, Me. It means 'I shall rise again'. Coolship Resurgam won a Silver medal at the 2010 GABF.", abv: "6.6")
# beer15 = Beer.create!(name: "Curieux", brewery_id: allagash.id, style: "Belgian", ibu: "27", description: "First brewed back in 2004, Curieux was our initial foray into barrel aging. To make Curieux, we take our Tripel and let it age in bourbon barrels for six-to-eight weeks. Once that time is up, we take the beer out of our cold cellars and blend it back with a portion of fresh Tripel. The resulting rich, golden ale features smooth notes of coconut, vanilla, and a hint of bourbon. ", abv: "10.4")

# beer16 = Beer.create!(name: "Pale Ale", brewery_id: sierra_nevada.id, style: "Pale Ale", ibu: "38", description: "Our most popular beer, Sierra Nevada Pale Ale is a delightful interpretation of a classic style. It has a deep amber color and an exceptionally full-bodied, complex character. Generous quantities of premium Cascade hops give the Pale Ale its fragrant bouquet and spicy flavor.", abv: "5.6")
# beer17 = Beer.create!(name: "Torpedo Extra IPA", brewery_id: sierra_nevada.id, style: "IPA", ibu: "65", description: "Sierra Nevada Torpedo Ale is a big American IPA; bold, assertive and full of flavor and aromas highlighting the complex citrus, pine and herbal character of whole-cone American hops. Our obsession with harnessing huge hop flavor led to the development of what we call the hop torpedo, a revolutionary method of dry-hopping designed, built, and debuted here at the brewery. Our torpedo is a sleek, stainless-steel piece of hardware that delivers more pure hop aroma than any method of dry-hopping we’ve ever seen.", abv: "7.2")
# beer18 = Beer.create!(name: "Kellerweis", brewery_id: sierra_nevada.id, style: "Wheat", ibu: "15", description: "One of the only American Hefeweizens made using the traditional Bavarian style of open fermentation. This difficult and labor-intensive technique adds uncommon depth and flavor complexity. A deeply flavorful hazy-golden hefeweizen, it is refreshing and perfect for a sunny day.", abv: "4.8")

# beer19 = Beer.create!(name: "Stone Xocoveza", brewery_id: stone.id, style: "Stout", ibu: "50", description: "This insanely delicious take on Mexican hot chocolate is crafted with cocoa, coffee, pasilla peppers, vanilla, cinnamon and nutmeg. First brewed in 2014 with San Diego homebrewer Chris Banker after his recipe was named the winner of our annual homebrew competition, it quickly became a cross-country sensation as craft beer media and fans cheered for Stone Xocoveza…and clamored for more. We too loved this beer, so of course we caroled ¡Claro que sí!", abv: "8.1")
# beer20 = Beer.create!(name: "Stone IPA", brewery_id: stone.id, style: "IPA", ibu: "71", description: "By definition, an India Pale Ale is hoppier and higher in alcohol than its little brother, pale ale — and we deliver in spades. Now one of the most well respected and best-selling IPAs in the country, this golden beauty explodes with citrusy flavor and hop aromas, all perfectly balanced by a subtle malt character.", abv: "6.9")
# beer21 = Beer.create!(name: "Stone Smoked Porter", brewery_id: stone.id, style: "Porter", ibu: "53", description: "Stone Smoked Porter is dark, rich and complicated. A porter is substantially darker than a pale ale, but not as black or opaque as a stout. Our Smoked porter has a captivatingly deep mahogany color, complimented by silky dark tan head. Rich, full bodied and robust. Smooth, with chocolate and coffee-like flavors balanced by the subtle smoky character of just the right amount of peat-smoked specialty malt.", abv: "5.9")

# beer22 = Beer.create!(name: "Sip of Sunshine", brewery_id: lawsons.id, style: "IPA", ibu: "65", description: "This lupulin-ladin India Pale Ale is packed with juicy tropical fruit character, bright floral aromas and delectable layers of hop flavor. Pour mindfully, inhale deeply and enjoy a tropical vacation in a glass. Always store cold, enjoy fresh and stay cool!", abv: "8")
# beer23 = Beer.create!(name: "Maple Nipple", brewery_id: lawsons.id, style: "Amber Ale", ibu: "25", description: "Our robust, rich maple ale is loaded with 100% pure Vermont maple syrup. It delivers a smooth and palate pleasing mouth feel with a slightly sticky finish!", abv: "8")
# beer24 = Beer.create!(name: "Super Session #8", brewery_id: lawsons.id, style: "IPA", ibu: "35", description: "Mosaic Hops", abv: "4.8")

# beer25 = Beer.create!(name: "Field 5 Golden IPA", brewery_id: gsb.id, style: "IPA", ibu: "70", description: "Follow these simple instructions on how to get the most enjoyment out of your can of Field 5 Golden IPA. By reading this can, you've already started your journey. Once you get back in your car, head east on Drexel Drive. Make a right on Fifth Avenue & head south to the third light. Make a right onto Spur Drive North & make a quick left onto the ramp for Southern State Parkway West. Take Exit 40 for Robert Moses Causeway. Continue south over both sets of bridges until you reach the traffic cirlce, take the second exit & continue onto Burma Road. When you see the sign for parking Field 5, make a right into the parking lot & head on out to the beach, find a nice relaxing spot, pop open this can & enjoy.", abv: "7")
# beer26 = Beer.create!(name: "Blood Orange Pale Ale", brewery_id: gsb.id, style: "Pale Ale", ibu: "40", description: "April 5, 2012: Remember back to the first time you ventured across the Great South Bay via the Robert Moses Causeway on your way to the beach? Well, we’ve captured that feeling in our Robert Moses Pale Ale! This well-balanced, sessionable American-style pale ale will keep you refreshed all year round. Whether you’re fishing on your boat, sitting around a campfire, or relaxing in your back yard, the fresh aroma of American hops paired with the crisp taste of the pale malts will bring you back every time. We’ve taken the Robert Moses Pale Ale that you’ve come to enjoy and took it to the next level with the addition of blood oranges to give it a slightly more citrus character with just the right amount of bitterness you’d expect from an American-style pale ale.", abv: "5")
# beer27 = Beer.create!(name: "Snaggletooth Stout", brewery_id: gsb.id, style: "Stout", ibu: "61", description: "Like its namesake, this beer is something you could get tangled up in.
# Brewed in limited quantities , especially popular during the colder months, this beer combines unique ingredients including roasted chocolate malt, flaked oats, cinnamon, licorice root and Long Island apples , culminating in a savory full-bodied malty goodness, and finishing with a hardy bite.", abv: "6.5")

# beer28 = Beer.create!(name: "Mary", brewery_id: hill_farmstead.id, style: "Pilsner", ibu: "60", description: "Mary was Edward's mother and our great-grandmother. A German-style pilsner brewed with our well water, German pilsner malt, our favorite German hops, and classic German lager yeast. 4.6% abv.", abv: "4.6")
# beer29 = Beer.create!(name: "Edward", brewery_id: hill_farmstead.id, style: "Pale Ale", ibu: "65", description: "Edward (1917-2002) is our grandfather; Hill Farmstead Brewery rests upon the land that was once home to him and his five children. In his honor, this American Pale Ale is dutifully crafted from American malted barley, a plethora of American hops, our ale yeast and water from Edward’s well. It is unfiltered and dry hopped. Aromatic and flowery, with impressions of citrus and pine, this is the ale that I dream to have shared with Edward. Pale and Caramel malt; Centennial, Chinook, Columbus, Simcoe, and Warrior hops; House Ale Yeast, and our Well Water. ", abv: "5.2")
# beer30 = Beer.create!(name: "Everett", brewery_id: hill_farmstead.id, style: "Porter", ibu: "30", description: "Everett (1908–1939) was our grandfather’s brother; Hill Farmstead Brewery rests upon the land that was once home to him and his 13 siblings. In his honor, this Porter is crafted from American malted barley, English and German roasted malts, American hops, our ale yeast, and water from our well. It is unfiltered and naturally carbonated. Decadent in its depth, with a complex backbone of chocolate, coffee, and malty sweetness, this is the ale that I dream to have shared with Everett.", abv: "7.5")

# beer31 = Beer.create!(name: "Rosé de Gambrinus", brewery_id: cantillon.id, style: "Sour", ibu: "10", description: "Beer with a slightly acidic, fruity and fragrant taste. Just like kriek, the 'fruitiness' of Rosé de Gambrinus is at its best when the beer is young. With age the lambic will take the upper hand, but this is at the expense of the fruit component.", abv: "5")
# beer32 = Beer.create!(name: "Classic Gueuze", brewery_id: cantillon.id, style: "Sour", ibu: "10", description: "Beer with a slightly acidic and fruity taste, delicate and woody fragrance and a dry finish that lingers on the palate. Beer with taste evolution that will keep for a long time in a good cellar.", abv: "5")
# beer33 = Beer.create!(name: "Cuvée Saint-Gilloise (Champions)", brewery_id: cantillon.id, style: "Sour", ibu: "8", description: "Cuvee des Champions is not a traditional ’gueuze,’ in that it is made from only two year-old 2001 lambic, not from a blend of older and younger lambics. It is also dry-hopped in the cask for three weeks with fresh Styrian Goldings hops. Re-fermentation in the bottle is achieved with the addition of a small amount of candi sugar.``", abv: "5")

# beer34 = Beer.create!(name: "Breakfast Stout", brewery_id: founders.id, style: "Stout", ibu: "60", description: "The coffee lover’s consummate beer. Brewed with an abundance of flaked oats, bitter and imported chocolates, and Sumatra and Kona coffee, this stout has an intense fresh-roasted java nose topped with a frothy, cinnamon-colored head that goes forever.", abv: "8.3")
# beer35 = Beer.create!(name: "Solid Gold", brewery_id: founders.id, style: "Pilsner", ibu: "20", description: "Our brewery was built on an attitude of no regrets. An attitude of taking risks to bring the best beer possible to our fellow renegades and rebels. Never brewing to style, but always brewing what we want to drink. Our take on a classic, Solid Gold is a drinkable premium lager brewed with the highest quality ingredients. Challenging what a lager can be? That’s something we won’t regret.", abv: "4.4")
# beer36 = Beer.create!(name: "All Day IPA", brewery_id: founders.id, style: "IPA", ibu: "42", description: "Satisfies your tastes while keeping your senses sharp. Brewed with a complex array of ingredients. Balanced for optimal aromatics and a clean finish.", abv: "4.7")

# beer37 = Beer.create!(name: "Zombie Dust", brewery_id: three_floyds.id, style: "Pale Ale", ibu: "50", description: "This intensely hopped and gushing undead Pale Ale will be one’s only respite after the zombie apocalypse. Created with our marvelous friends in the comic industry.", abv: "6.2")
# beer38 = Beer.create!(name: "Gumballhead", brewery_id: three_floyds.id, style: "Wheat", ibu: "35", description: "An American wheat ale brewed with white wheat and dry hopped with hand-selected hops from the Yakima Valley. Bright and refreshing with a lemony finish.", abv: "5.6")
# beer39 = Beer.create!(name: "Alpha King", brewery_id: three_floyds.id, style: "Pale Ale", ibu: "68", description: "A bold yet balanced American Pale Ale with slight caramel sweetness and aggressive citrus hoppiness. This is our flagship beer.", abv: "6.66")

# beer40 = Beer.create!(name: "Velvet Merlin", brewery_id: firestone_walker.id, style: "Stout", ibu: "27", description: "A decadent oatmeal stout. Velvet Merlin offers robust cocoa and espresso aromas with subtle American hop nuances. Rich dark chocolate and roasted coffee flavor with a creamy mouth feel and wonderfully dry finish create the perfect balance in this full-bodied stout. Ideal for sipping in the winter months or at the end of a meal.", abv: "5.5")
# beer41 = Beer.create!(name: "DBA (Double Barrel Ale)", brewery_id: firestone_walker.id, style: "Pale Ale", ibu: "30", description: "A British Pale Ale never tasted so fresh. We challenge our good friends across the pond to match this one. We've honored the traditions of the great British Pale brewers of Burton-on-Trent using our patented Firestone Union oak barrels. You're left with a mild blend of vanilla and toasted oak flavor touched with an elegant hint of English noble hops. DBA is the flagship of our company and wildly popular.", abv: "5")
# beer42 = Beer.create!(name: "Union Jack IPA", brewery_id: firestone_walker.id, style: "IPA", ibu: "70", description: "An aggressively hopped West Coast-style IPA. Union Jack showcases exceptional dry hop character with stunning pineapple, citrus and piney aromas on the nose accompanied by honey-like malt aromatics. Double dry hopping brings bold grapefruit, tangerine and citrus flavors that are contrasted by pale malt sweetness to balance this intense brew. A true tribute to the style that put the West Coast on the craft beer map.", abv: "7")

# beer43 = Beer.create!(name: "Funk Metal", brewery_id: jester_king.id, style: "Sour", ibu: "60", description: "Funk Metal is an 8.2% alcohol, unfiltered, unpasteurized, naturally conditioned imperial stout fermented with farmhouse yeast, aged for months in oak barrels with wild yeast and souring bacteria, and then hand-blended with other barrel-aged beer to round out the palate. The finished beer retains aromas of chocolate and roast but takes on a distinct vinous character and sour complexity from extended aging and fermentation in oak barrels.", abv: "7.2")
# beer44 = Beer.create!(name: "Atrial Rubicite", brewery_id: jester_king.id, style: "Sour", ibu: "15", description: "Atrial Rubicite is made from well water, barley, wheat, hops, farmhouse, native yeast from the Texas Hill Country, souring bacteria and raspberries. It’s 5.8% alcohol by volume, has a finishing gravity of 1.005 and is 3.36 pH. It is unfiltered, unpasteurized and 100% bottle conditioned.", abv: "5.8")
# beer45 = Beer.create!(name: "Moderne Dansk", brewery_id: jester_king.id, style: "Sour", ibu: "8", description: "Wild ale aged in Danish cherry wine barrels refermented with Danish Stevnsbær cherry juice!", abv: "7.1")

# beer46 = Beer.create!(name: "Vicinity", brewery_id: trillium.id, style: "IPA", ibu: "65", description: "Originally brewed in celebration of the first anniversary of Row 34, our favorite Fort Point oyster bar and craft-beer purveyor, Vicinity highlights a neighborhood collaboration of passion and vision. The beer's appearance is a yellow straw-color, with a significant haze. Heavy citrus aromas of pineapple, orange flesh and mango dance on the nose and palate. The pilsner malt provides a medium body and wraps up each sip with a slight balancing bitterness.", abv: "8")
# beer47 = Beer.create!(name: "Congress Street", brewery_id: trillium.id, style: "IPA", ibu: "65", description: "Our flagship American IPA highlights the distinctively aromatic Australian Galaxy hop. The nose bursts with pine, citrus rind, melon and pineapple. Pronounced flavors of peach, clementine, and tropical fruits are accentuated with moderate bitterness and balanced by a light, biscuity malt character.", abv: "7.2")
# beer48 = Beer.create!(name: "Fort Point", brewery_id: trillium.id, style: "Pale Ale", ibu: "40", description: "Our signature American pale ale balances light, crisp, malt character with an abundance of hop-derived aromatics and flavors from the use of Citra and Columbus. The fragrant nose is fresh citrus, tropical fruit, and peach. Bold flavors of pineapple and mango mix with dank notes of zesty citrus and fresh pine needles. With the smooth mouthfeel, gentle bitterness, and dry finish, Fort Point is our standard daily-drinker.", abv: "6.6")

# beer49 = Beer.create!(name: "Julius", brewery_id: tree_house.id, style: "IPA", ibu: "72", description: "Bursting with pungent American hops, Julius - our flagship American IPA - is a bright, juicy beer filled with flavors and aromas of mango, peach, passionfruit, and a melange of citrus juice. A soft, pillowy mouthfeel and rounded bitterness ensure Julius will never tire the palate - a true joy to drink! ", abv: "6.8")
# beer50 = Beer.create!(name: "Green", brewery_id: tree_house.id, style: "IPA", ibu: "90", description: "Our cross-continental IPA! Made with Australian and American hops, this tropical heavy IPA opens up in the glass with notes of hugely flavorful notes of lemon-lime, pineapple, orange sorbet, and tangerine. It has a soft but pointed bitterness and a rich, velvety mouth feel. Intensely kettle and dry hopped yet balanced and flavorful, Green is a beloved crew favorite here at Tree House!", abv: "7.5")
# beer51 = Beer.create!(name: "Haze", brewery_id: tree_house.id, style: "IPA", ibu: "90", description: "Our Double IPA! We smell a ton of peach on the nose, with complimentary notes of orange and passionfruit. The flavor is similar with a blast of citrus fruit & peach quickly followed by a bounty of tropical fruit. A lingering and pleasant saturated hop oil finish awaits. . . . A real juice bomb of a beer! ", abv: "8.2")

# beer52 = Beer.create!(name: "Lagerbier Hell", brewery_id: augustiner.id, style: "Helles Lager", ibu: "12", description: "Ein besonders mildes, spritziges, lang gelagertes und vor allem erfrischendes Bier. Einmalig in seinem Geschmack, ein Genuss für jeden Bierkenner.", abv: "5.2")
# beer53 = Beer.create!(name: "Weissbier", brewery_id: augustiner.id, style: "Wheat", ibu: "14", description: "Das bernsteinfarbene Hefeweißbier, nach altbewährten Verfahren aus sorgfältigst ausgewählten Rohstoffen gebraut. In Flaschengärung, bis zur vollen Spitzenreife in den Brauereigewölbekellern gelagert und sorgsam gepflegt, erhält dieses Bier seine Frische und den feinwürzigen Geschmack.", abv: "5.4")

# beer54 = Beer.create!(name: "Lagunitas Sucks", brewery_id: lagunitas.id, style: "IPA", ibu: "63", description: "This beer is a 'cereal medley' of barley, rye, wheat, and oats. Full of complexishness from the 4 grains, then joyously dry-hopped for that big aroma and resinous flavor.", abv: "8")
# beer55 = Beer.create!(name: "Hop Stoopid", brewery_id: lagunitas.id, style: "IPA", ibu: "102", description: "The beer with a guarantee built right into the name, this one is destined to blast through the flavors from the night before. Massively dry-hopped for your aromatic pleasure. ", abv: "8")
# beer56 = Beer.create!(name: "Pils", brewery_id: lagunitas.id, style: "Pilsner", ibu: "35", description: "Our only Unlimited Lager, brewed with loads of imported Saaz hops and a bottom-fermenting yeast strain that leaves it Light and Crisp and Easy to Slam, yet full of real flavor and all the things you yearn for.", abv: "6")

# beer57 = Beer.create!(name: "Hoponius Union", brewery_id: jacks_abbey.id, style: "IPL", ibu: "65", description: "Hoponius Union harmoniously combines lager yeast fermentation and West Coast IPA hops. Our flagship hoppy lager is like a traditional IPA but with a twist – it’s fermented cold and aged for extended periods. A blend of classic American hops creates a huge tropical fruit and citrusy hop aroma. A dry finish accentuates the pleasant bitterness and hop profile.", abv: "6.5")
# beer58 = Beer.create!(name: "Kiwi Rising", brewery_id: jacks_abbey.id, style: "IPL", ibu: "105", description: "Kiwi Rising is a double IPL dry-hopped with over four pounds of New Zealand hops per barrel. Expect intense notes of white grape, ripe melon, and bright citrus by way of Nelson Sauvin, Waimea, and Motueka hops. While this beer might taste like a fresh and juicy kiwifruit, it doesn't actually contain any.", abv: "8.5")
# beer59 = Beer.create!(name: "House Lager", brewery_id: jacks_abbey.id, style: "Helles Lager", ibu: "18", description: "What the Helles is a Landbier? Ours is sweet and golden with a full malty body, inspired by the country lagers of Bavaria. This Pale Bier is our House specialty. From Jack’s House to Your House!", abv: "5.2")

# Checkin Seeds

checkin = Checkin.create!(author_id: demo_user.id, body: "This. Tastes. Good. To Me", beer_id: beer2.id, rating: 4.25)
checkin = Checkin.create!(author_id: demo_user.id, body: "Pretty darn good beer!", beer_id: beer1.id, rating: 3.75)
checkin = Checkin.create!(author_id: user1.id, body: "First checkin!!!!!!!!", beer_id: beer3.id, rating: 4)
checkin = Checkin.create!(author_id: user1.id, body: "BEST BEER EVERRR", beer_id: beer2.id, rating: 5)
checkin = Checkin.create!(author_id: user2.id, body: "", beer_id: beer6.id, rating: 3.5)
checkin = Checkin.create!(author_id: user2.id, body: "This beer is not for me.", beer_id: beer7.id, rating: 2.5)
checkin = Checkin.create!(author_id: user3.id, body: "Eh, I've brewed better.", beer_id: beer4.id, rating: 3.5)
checkin = Checkin.create!(author_id: user3.id, body: "BRB grabbing another!", beer_id: beer9.id, rating: 4)

# user_pic = open('https://lagerd-seeds.s3.us-east-2.amazonaws.com/default_user_img.png')
# beer_pic = open('https://lagerd-seeds.s3.us-east-2.amazonaws.com/default_beer.png')
# brewery_pic = open('https://lagerd-seeds.s3.us-east-2.amazonaws.com/default_brewery.png')

# demo_user.photo.attach(io: open('https://lagerd-seeds.s3.us-east-2.amazonaws.com/default_user_img.png'), filename: 'default_user_img.png')
# user1.photo.attach(io: open('https://lagerd-seeds.s3.us-east-2.amazonaws.com/default_user_img.png'), filename: 'default_user_img.png')
# user2.photo.attach(io: open('https://lagerd-seeds.s3.us-east-2.amazonaws.com/default_user_img.png'), filename: 'default_user_img.png')
# user3.photo.attach(io: open('https://lagerd-seeds.s3.us-east-2.amazonaws.com/default_user_img.png'), filename: 'default_user_img.png')
# user4.photo.attach(io: open('https://lagerd-seeds.s3.us-east-2.amazonaws.com/default_user_img.png'), filename: 'default_user_img.png')
# user5.photo.attach(io: open('https://lagerd-seeds.s3.us-east-2.amazonaws.com/default_user_img.png'), filename: 'default_user_img.png')

# other_half.photo.attach(io: open('https://lagerd-seeds.s3.us-east-2.amazonaws.com/default_brewery.png'), filename: 'default_brewery.png')
# grimm.photo.attach(io: open('https://lagerd-seeds.s3.us-east-2.amazonaws.com/default_brewery.png'), filename: 'default_brewery.png')
# russian_river.photo.attach(io: open('https://lagerd-seeds.s3.us-east-2.amazonaws.com/default_brewery.png'), filename: 'default_brewery.png')
# alchemist.photo.attach(io: open('https://lagerd-seeds.s3.us-east-2.amazonaws.com/default_brewery.png'), filename: 'default_brewery.png')
# allagash.photo.attach(io: open('https://lagerd-seeds.s3.us-east-2.amazonaws.com/default_brewery.png'), filename: 'default_brewery.png')
# sierra_nevada.photo.attach(io: open('https://lagerd-seeds.s3.us-east-2.amazonaws.com/default_brewery.png'), filename: 'default_brewery.png')
# stone.photo.attach(io: open('https://lagerd-seeds.s3.us-east-2.amazonaws.com/default_brewery.png'), filename: 'default_brewery.png')
# lawsons.photo.attach(io: open('https://lagerd-seeds.s3.us-east-2.amazonaws.com/default_brewery.png'), filename: 'default_brewery.png')
# gsb.photo.attach(io: open('https://lagerd-seeds.s3.us-east-2.amazonaws.com/default_brewery.png'), filename: 'default_brewery.png')
# hill_farmstead.photo.attach(io: open('https://lagerd-seeds.s3.us-east-2.amazonaws.com/default_brewery.png'), filename: 'default_brewery.png')
# cantillon.photo.attach(io: open('https://lagerd-seeds.s3.us-east-2.amazonaws.com/default_brewery.png'), filename: 'default_brewery.png')
# founders.photo.attach(io: open('https://lagerd-seeds.s3.us-east-2.amazonaws.com/default_brewery.png'), filename: 'default_brewery.png')
# three_floyds.photo.attach(io: open('https://lagerd-seeds.s3.us-east-2.amazonaws.com/default_brewery.png'), filename: 'default_brewery.png')
# firestone_walker.photo.attach(io: open('https://lagerd-seeds.s3.us-east-2.amazonaws.com/default_brewery.png'), filename: 'default_brewery.png')
# jester_king.photo.attach(io: open('https://lagerd-seeds.s3.us-east-2.amazonaws.com/default_brewery.png'), filename: 'default_brewery.png')
# trillium.photo.attach(io: open('https://lagerd-seeds.s3.us-east-2.amazonaws.com/default_brewery.png'), filename: 'default_brewery.png')
# tree_house.photo.attach(io: open('https://lagerd-seeds.s3.us-east-2.amazonaws.com/default_brewery.png'), filename: 'default_brewery.png')
# augustiner.photo.attach(io: open('https://lagerd-seeds.s3.us-east-2.amazonaws.com/default_brewery.png'), filename: 'default_brewery.png')
# lagunitas.photo.attach(io: open('https://lagerd-seeds.s3.us-east-2.amazonaws.com/default_brewery.png'), filename: 'default_brewery.png')
# jacks_abbey.photo.attach(io: open('https://lagerd-seeds.s3.us-east-2.amazonaws.com/default_brewery.png'), filename: 'default_brewery.png')

# beer1.photo.attach(io: open('https://lagerd-seeds.s3.us-east-2.amazonab.com/default_beer.png'), filename: 'default_beer.png')
# beer10.photo.attach(io: open('https://lagerd-seeds.s3.us-east-2.amazonaws.com/default_beer.png'), filename: 'default_beer.png')
# beer11.photo.attach(io: open('https://lagerd-seeds.s3.us-east-2.amazonaws.com/default_beer.png'), filename: 'default_beer.png')
# beer12.photo.attach(io: open('https://lagerd-seeds.s3.us-east-2.amazonaws.com/default_beer.png'), filename: 'default_beer.png')
# beer13.photo.attach(io: open('https://lagerd-seeds.s3.us-east-2.amazonaws.com/default_beer.png'), filename: 'default_beer.png')
# beer14.photo.attach(io: open('https://lagerd-seeds.s3.us-east-2.amazonaws.com/default_beer.png'), filename: 'default_beer.png')
# beer15.photo.attach(io: open('https://lagerd-seeds.s3.us-east-2.amazonaws.com/default_beer.png'), filename: 'default_beer.png')
# beer16.photo.attach(io: open('https://lagerd-seeds.s3.us-east-2.amazonaws.com/default_beer.png'), filename: 'default_beer.png')
# beer17.photo.attach(io: open('https://lagerd-seeds.s3.us-east-2.amazonaws.com/default_beer.png'), filename: 'default_beer.png')
# beer18.photo.attach(io: open('https://lagerd-seeds.s3.us-east-2.amazonaws.com/default_beer.png'), filename: 'default_beer.png')
# beer19.photo.attach(io: open('https://lagerd-seeds.s3.us-east-2.amazonaws.com/default_beer.png'), filename: 'default_beer.png')
# beer20.photo.attach(io: open('https://lagerd-seeds.s3.us-east-2.amazonaws.com/default_beer.png'), filename: 'default_beer.png')
# beer21.photo.attach(io: open('https://lagerd-seeds.s3.us-east-2.amazonaws.com/default_beer.png'), filename: 'default_beer.png')
# beer22.photo.attach(io: open('https://lagerd-seeds.s3.us-east-2.amazonaws.com/default_beer.png'), filename: 'default_beer.png')
# beer23.photo.attach(io: open('https://lagerd-seeds.s3.us-east-2.amazonaws.com/default_beer.png'), filename: 'default_beer.png')
# beer24.photo.attach(io: open('https://lagerd-seeds.s3.us-east-2.amazonaws.com/default_beer.png'), filename: 'default_beer.png')
# beer25.photo.attach(io: open('https://lagerd-seeds.s3.us-east-2.amazonaws.com/default_beer.png'), filename: 'default_beer.png')
# beer26.photo.attach(io: open('https://lagerd-seeds.s3.us-east-2.amazonaws.com/default_beer.png'), filename: 'default_beer.png')
# beer27.photo.attach(io: open('https://lagerd-seeds.s3.us-east-2.amazonaws.com/default_beer.png'), filename: 'default_beer.png')
# beer28.photo.attach(io: open('https://lagerd-seeds.s3.us-east-2.amazonaws.com/default_beer.png'), filename: 'default_beer.png')
# beer29.photo.attach(io: open('https://lagerd-seeds.s3.us-east-2.amazonaws.com/default_beer.png'), filename: 'default_beer.png')
# beer30.photo.attach(io: open('https://lagerd-seeds.s3.us-east-2.amazonaws.com/default_beer.png'), filename: 'default_beer.png')
# beer31.photo.attach(io: open('https://lagerd-seeds.s3.us-east-2.amazonaws.com/default_beer.png'), filename: 'default_beer.png')
# beer32.photo.attach(io: open('https://lagerd-seeds.s3.us-east-2.amazonaws.com/default_beer.png'), filename: 'default_beer.png')
# beer33.photo.attach(io: open('https://lagerd-seeds.s3.us-east-2.amazonaws.com/default_beer.png'), filename: 'default_beer.png')
# beer34.photo.attach(io: open('https://lagerd-seeds.s3.us-east-2.amazonaws.com/default_beer.png'), filename: 'default_beer.png')
# beer35.photo.attach(io: open('https://lagerd-seeds.s3.us-east-2.amazonaws.com/default_beer.png'), filename: 'default_beer.png')
# beer36.photo.attach(io: open('https://lagerd-seeds.s3.us-east-2.amazonaws.com/default_beer.png'), filename: 'default_beer.png')
# beer37.photo.attach(io: open('https://lagerd-seeds.s3.us-east-2.amazonaws.com/default_beer.png'), filename: 'default_beer.png')
# beer38.photo.attach(io: open('https://lagerd-seeds.s3.us-east-2.amazonaws.com/default_beer.png'), filename: 'default_beer.png')
# beer39.photo.attach(io: open('https://lagerd-seeds.s3.us-east-2.amazonaws.com/default_beer.png'), filename: 'default_beer.png')
# beer40.photo.attach(io: open('https://lagerd-seeds.s3.us-east-2.amazonaws.com/default_beer.png'), filename: 'default_beer.png')
# beer41.photo.attach(io: open('https://lagerd-seeds.s3.us-east-2.amazonaws.com/default_beer.png'), filename: 'default_beer.png')
# beer42.photo.attach(io: open('https://lagerd-seeds.s3.us-east-2.amazonaws.com/default_beer.png'), filename: 'default_beer.png')
# beer43.photo.attach(io: open('https://lagerd-seeds.s3.us-east-2.amazonaws.com/default_beer.png'), filename: 'default_beer.png')
# beer44.photo.attach(io: open('https://lagerd-seeds.s3.us-east-2.amazonaws.com/default_beer.png'), filename: 'default_beer.png')
# beer45.photo.attach(io: open('https://lagerd-seeds.s3.us-east-2.amazonaws.com/default_beer.png'), filename: 'default_beer.png')
# beer46.photo.attach(io: open('https://lagerd-seeds.s3.us-east-2.amazonaws.com/default_beer.png'), filename: 'default_beer.png')
# beer47.photo.attach(io: open('https://lagerd-seeds.s3.us-east-2.amazonaws.com/default_beer.png'), filename: 'default_beer.png')
# beer48.photo.attach(io: open('https://lagerd-seeds.s3.us-east-2.amazonaws.com/default_beer.png'), filename: 'default_beer.png')
# beer49.photo.attach(io: open('https://lagerd-seeds.s3.us-east-2.amazonaws.com/default_beer.png'), filename: 'default_beer.png')
# beer50.photo.attach(io: open('https://lagerd-seeds.s3.us-east-2.amazonaws.com/default_beer.png'), filename: 'default_beer.png')
# beer51.photo.attach(io: open('https://lagerd-seeds.s3.us-east-2.amazonaws.com/default_beer.png'), filename: 'default_beer.png')
# beer52.photo.attach(io: open('https://lagerd-seeds.s3.us-east-2.amazonaws.com/default_beer.png'), filename: 'default_beer.png')
# beer53.photo.attach(io: open('https://lagerd-seeds.s3.us-east-2.amazonaws.com/default_beer.png'), filename: 'default_beer.png')
# beer54.photo.attach(io: open('https://lagerd-seeds.s3.us-east-2.amazonaws.com/default_beer.png'), filename: 'default_beer.png')
# beer55.photo.attach(io: open('https://lagerd-seeds.s3.us-east-2.amazonaws.com/default_beer.png'), filename: 'default_beer.png')
# beer56.photo.attach(io: open('https://lagerd-seeds.s3.us-east-2.amazonaws.com/default_beer.png'), filename: 'default_beer.png')
# beer57.photo.attach(io: open('https://lagerd-seeds.s3.us-east-2.amazonaws.com/default_beer.png'), filename: 'default_beer.png')
# beer58.photo.attach(io: open('https://lagerd-seeds.s3.us-east-2.amazonaws.com/default_beer.png'), filename: 'default_beer.png')
# beer59.photo.attach(io: open('https://lagerd-seeds.s3.us-east-2.amazonaws.com/default_beer.png'), filename: 'default_beer.png')